Dev/fe
prod-des-project-2021/group_1 pull request #2
Opened 2021-11-08 19:48 UTC by ngocdu171

install dependencies

2021-11-08 20:00 UTC, thinhnguyen5 approved these changes

2021-11-09 07:17 UTC, toilavic commented
NOTE: No merge until everything on this brand works perfectly

2021-11-09 07:19 UTC, toilavic reviewed
LGTM!

2021-11-15 15:51 UTC, toilavic reviewed
test

2021-11-15 21:07 UTC, toilavic requested changes
Check our those comments and fix it. 
After fix one comment, push to the dev/FE, and comeback to the corresponding comment then mark them as resolved. I will check it again in the new commit

2021-11-15 21:07 UTC, toilavic commented on frontend/src/data/stores/interfaceStore.ts
> +    lat: number,
why do you duplicated those interfaces? What is the purpose of IStores?

2021-11-15 21:07 UTC, toilavic commented on frontend/src/data/stores/stores.ts
> +import interfaceStore from "./interfaceStore";
You can still using the mock data for the open-map. But make sure to delete it when we have the real data from backend side. 
Please check our the Backend tickets in Jira

2021-11-15 21:07 UTC, toilavic commented on frontend/src/data/users/interfaceUser.ts
> +export default interface interfaceUser {
Remember to checkout the backend ticket in Jira. The constructor will be changed with the new type and permission

2021-11-15 21:07 UTC, toilavic commented on frontend/src/data/users/users.ts
> +import interfaceUser from "./interfaceUser";
Remove the mock data

2021-11-15 21:07 UTC, toilavic commented on frontend/src/pages/login/Login.tsx
> +    Login(email, password);
when apply the new API, please remember to use async await to wait for the responce.

2021-11-15 21:07 UTC, toilavic commented on frontend/src/pages/map/MapPage.tsx
> +            {test.map((tam) => {
Meaningless name variables

2021-11-15 21:07 UTC, toilavic commented on frontend/src/pages/register/Register.tsx
> +    const handleRegister = (event:ChangeEvent<HTMLInputElement>) => {
remember to add register API to the callback. Use async await for the backend

2021-11-18 16:10 UTC, ngocdu171 commented on frontend/src/components/showmap/Showmap.tsx
> +    const [selectedRestaurant, setSelectedRestaurant]:any = useState(null);
done

2021-11-18 16:34 UTC, ngocdu171 commented on frontend/src/components/showmap/Showmap.tsx
> +            height = {650}
define mapbox token in constant.tsx

2021-11-24 20:30 UTC, toilavic commented
We have a huge code debt in this branch, and also a lot of meaningless commits and separated PRs.
Need an update for this branch

2021-11-25 15:34 UTC, toilavic commented
_Always a good idea to try to step into someone else's shoes_. "Do I understand what this variable means?" "Do I understand what this code is doing?"  "Do I understand what kind of commits are doing?"
**Making the those things descriptive never hurts anyone!!!**

2021-12-10 08:59 UTC, toilavic commented
Close, now use hotfix to be primary branch

2021-12-10 08:59 UTC, closed without merging